### ISSUE TITLE
[Refactor] 프로젝트 코드 정리

### ISSUE THREAD

**Issue by YunKi-H** [DeveloperAcademy-POSTECH/2024-MacC-A18-Krabs#153]
## Description

프로젝트 정리 하고 갑니당

## TODO

- [ ] 안쓰는 파일 제거
- [ ] 쓸데없는 주석 제거
- [ ] 코드 컨벤션 맞추기
- [ ] 혹시나 폴더링 이상하면 고치기
- [ ] Extension으로 분리할 수 있는부분 분리해보기
- [ ] 기타 수정사항
